# Generated by Django 5.2.5 on 2025-08-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrecommendation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pricingmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesforecast',
            name='product',
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='product',
        ),
    ]
